server:
  port: 9111
spring:
  session:
    store-type: none
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: admin
    timeout: 1000
    jedis:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 5
